# src/adto/__init__.pyi
"""Type stubs for adto package"""


def solve(K, F): ...
def assemble_stiffness_matrix_parts(*args, **kwargs): ...
def compute_compliance_differentiable(*args, **kwargs): ...
def bisection_differentiable(*args, **kwargs): ...
def apply_density_filter(x, radius): ...
def volume_enforcing_filter(*args, **kwargs): ...
def reduce_K(*args, **kwargs): ...
